version: '2'

volumes:
  node-red-data:
  grafana-data:
  influxdb-data:
  influxdb-etc:

services:
    # ------------------------------------------------------------------------------------
    # RASPTANK
    # ------------------------------------------------------------------------------------
    rasptank:
        privileged: true
        build: ./rasptank
        restart: always
        network_mode: host   
        expose:
            - "10123"
            - "8888" 
            - "10223"


    # ------------------------------------------------------------------------------------
    # BLED112 to connect to BrainBit
    # ------------------------------------------------------------------------------------
    brainbitbled112:
        privileged: true
        build: ./brainbitbled112
        restart: always
        network_mode: host       
        depends_on:
        - influxdb
        - grafana        
    # ------------------------------------------------------------------------------------
    # InfluxDB Database for storing data
    # ------------------------------------------------------------------------------------

    influxdb:
        image: influxdb@sha256:73f876e0c3bd02900f829d4884f53fdfffd7098dd572406ba549eed955bf821f
        container_name: influxdb
        restart: always
        ports:
            - "8086:8086"        
        environment:
        - INFLUXDB_DB=balena
        - INFLUXDB_USER=balena
        - INFLUXDB_ADMIN_ENABLED=true
        - INFLUXDB_ADMIN_USER=admin
        - INFLUXDB_ADMIN_PASSWORD=admin
        - INFLUXDB_DATA_DIR=/data
        volumes:
            - influxdb-data:/var/lib/influxdb
            - influxdb-etc:/etc/influxdb

    # ------------------------------------------------------------------------------------
    # MQTT Broker
    # ------------------------------------------------------------------------------------
    #mqtt:
    #    image: eclipse-mosquitto:latest
    #    ports:
    #    - "1883:1883"
    #    restart: always      


    # ------------------------------------------------------------------------------------
    # Grafana
    # ------------------------------------------------------------------------------------
    grafana:
        image: bh.cr/balenalabs/dashboard
        container_name: grafana
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - "grafana-data:/data"
            
